In [1]:
!pip install -U plotly

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in /home/youx/.local/lib/python3.10/site-packages (6.5.1)
Collecting plotly
  Downloading plotly-6.5.2-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 18.5 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: narwhals>=1.15.1 in /home/youx/.local/lib/python3.10/site-packages (from plotly) (2.15.0)
Requirement already satisfied: packaging in /home/youx/.local/lib/python3.10/site-packages (from plotly) (25.0)
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 6.5.1
    Uninstalling plotly-6.5.1:
      Successfully uninstalled plotly-6.5.1
Successfully installed plotly-6.5.2

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
px.line(x=[1, 2, 3, 4, 5,], y=[10, 40, 20, 50, 5])

## Utilizando DataFrame

In [4]:
df = pd.read_csv("flights.csv")

In [5]:
df.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [6]:
df.tail()

     year      month  passengers
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

In [7]:
df_agrupado_pelo_mes = df.groupby("month", sort=False).mean().reset_index()

In [8]:
df_agrupado_pelo_mes.head()

      month    year  passengers
0   January  1954.5  241.750000
1  February  1954.5  235.000000
2     March  1954.5  270.166667
3     April  1954.5  267.083333
4       May  1954.5  271.833333

In [9]:
px.line(df_agrupado_pelo_mes, x="month", y="passengers")

In [10]:
df.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [11]:
px.line(df, x="month", y="passengers", color="year")