In [5]:
import numpy as np
import pandas as pd
import plotly.express as px

In [6]:
px.line(x=[1,2,3,4,5] ,y=[10,40,20,50,5])

In [7]:
df = pd.read_csv('flights .csv')
df.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [8]:
df.tail()

     year      month  passengers
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

In [9]:
df_agrupado_pelo_mes=df.groupby('month',sort=False).mean().reset_index()

In [10]:
px.line(df_agrupado_pelo_mes,x='month',y='passengers')

In [11]:
df.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [12]:
px.line(df,x='month',y='passengers',color='year')

# 
02-GRAFICO DE BARRAS

In [13]:
import numpy as np
import pandas as pd
import plotly.express as px

In [14]:
df= pd.read_csv('tips.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

# GRAFICO DE BARRAS

In [16]:
df_agrupado_pelo_dia = df.groupby('day').agg({'total_bill':np.sum}).reset_index()

/tmp/ipykernel_55593/216401516.py:1: FutureWarning:

The provided callable <function sum at 0x7e353012b370> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

In [17]:
df_agrupado_pelo_dia

    day  total_bill
0   Fri      325.88
1   Sat     1778.40
2   Sun     1627.16
3  Thur     1096.33

In [18]:
px.bar(df_agrupado_pelo_dia, x= 'day', y='total_bill')

In [19]:
df_agrupado_pelo_dia_e_sexo = df.groupby(['day','sex'],sort=False).agg({'total_bill':np.sum}).reset_index()

/tmp/ipykernel_55593/1753039077.py:1: FutureWarning:

The provided callable <function sum at 0x7e353012b370> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

In [20]:
df_agrupado_pelo_dia_e_sexo

    day     sex  total_bill
0   Sun  Female      357.70
1   Sun    Male     1269.46
2   Sat    Male     1227.35
3   Sat  Female      551.05
4  Thur    Male      561.44
5  Thur  Female      534.89
6   Fri    Male      198.57
7   Fri  Female      127.31

In [21]:
px.bar(df_agrupado_pelo_dia_e_sexo ,x='day',y='total_bill',color='sex',barmode='group')

In [22]:
px.bar(df_agrupado_pelo_dia_e_sexo ,x='total_bill',y='day',color='sex',barmode='group')

# GRAFICO DE DISPERSÃ0

In [23]:
px.scatter(df, x='total_bill', y='tip',color='day',hover_name='time')

# Grafico de Pizza

In [24]:
quantidade_de_pedidos_no_dia = df['day'].value_counts()

In [25]:
quantidade_de_pedidos_no_dia

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [26]:
quantidade_de_pedidos_no_dia.index

Index(['Sat', 'Sun', 'Thur', 'Fri'], dtype='object', name='day')

In [27]:
px.pie(quantidade_de_pedidos_no_dia, names=quantidade_de_pedidos_no_dia.index,values=quantidade_de_pedidos_no_dia.values)

# 03. Grafico Estatísticos- Parte |

In [28]:

import pandas as pd
import plotly.express as px

In [29]:
df = pd.read_csv('tips.csv')

In [30]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# 3.1.Histogramas

In [31]:
px.histogram(
    df,
    x='total_bill',
    color='time',
    nbins=50,
    histnorm='probability density',
    marginal='box',
    title='Histograma da taxa paga no restaurante',
    color_discrete_sequence=['green', 'purple']
)

# 3.2 Distribuição

In [32]:
import plotly.figure_factory as ff
import  numpy as np

In [33]:
x1 = np.random.randn(1000)
x2 = np.random.randn(1000)+ 5

In [34]:
ff.create_distplot([x1,x2],group_labels = ['Normal 1','Normal 2'])

ImportError: FigureFactory.create_distplot requires scipy