# Fundamentos de Estatísticas Básica

In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statistics

#### Implementação em Python

Exemplo 1:

In [54]:
notas = [7, 8, 6, 10]
soma = sum(notas)
media = soma /len(notas)
print(f"A média do aluno foi: {media}")

A média do aluno foi: 7.75

Exemplo 2:

In [55]:
endividamento = [ 25, 51, 76, 41, 55, 13]
def calcular_media(vetor):
    return sum(vetor) / len(vetor)
print(f"A média do endividamento das empresas foi: {calcular_media(endividamento)}%")

A média do endividamento das empresas foi: 43.5%

Exemplo 3:

In [56]:
vendas = [10, 17, 13, 300]
calcular_media(vendas)

85.0

### Média Aritimética ponderada

- 718,91 (Peso 5)
- 521,33 (Peso 2)
- 627,9 (Peso 2)
- 610,12 (Peso 4)
- 930 (Peso 5)

Exemplo 4:

In [57]:
notas = [718.91, 521.33, 627.9, 610.12, 930]
pesos = [5, 2, 2, 4, 5]

In [58]:
np.average(notas, weights = pesos)

np.float64(721.305)

##### Mediana

Exemplo 5:

In [59]:
conjunto_A = [10, 10, 11, 13, 87]
conjunto_B = [23, 31, 17, 18]

In [60]:
np.median(conjunto_A)

np.float64(11.0)

In [61]:
np.mean(conjunto_A)

np.float64(26.2)

In [62]:
np.median(conjunto_B)

np.float64(20.5)

In [63]:
np.mean(conjunto_B)

np.float64(22.25)

#### Moda

In [64]:
a = [11, 2, 2, 9, 7]
b = [4, 4, 19]
c = [3, 3, 1, 9, 9]

In [65]:
statistics.mode(a)

2

In [66]:
statistics.mode(b)

4

In [67]:
statistics.multimode(c)

[3, 9]

### Medidas de dispersão e associação

In [68]:
B = [5, 8, 10, 12, 15]

In [69]:
np.var(B)

np.float64(11.6)

# Implementações com a biblioteca Pandas

In [70]:
dados = {'A': [1, 22, 1, 90],
        'B': [40, 45, 47, 49],
        'C': [15, 22, 33, 4]
        }

In [71]:
df = pd.DataFrame(dados)

In [72]:
df

    A   B   C
0   1  40  15
1  22  45  22
2   1  47  33
3  90  49   4

In [73]:
df.max()

A    90
B    49
C    33
dtype: int64

In [74]:
df.max(axis = 1)

0    40
1    45
2    47
3    90
dtype: int64

In [75]:
df.min()

A     1
B    40
C     4
dtype: int64

In [76]:
df.sum()

A    114
B    181
C     74
dtype: int64

In [77]:
df.mean()

A    28.50
B    45.25
C    18.50
dtype: float64

In [78]:
df.var()

A    1779.000000
B      14.916667
C     148.333333
dtype: float64

In [79]:
df.std()

A    42.178193
B     3.862210
C    12.179217
dtype: float64

In [ ]:
df.describe().T

   count   mean        std   min    25%   50%    75%   max
A    4.0  28.50  42.178193   1.0   1.00  11.5  39.00  90.0
B    4.0  45.25   3.862210  40.0  43.75  46.0  47.50  49.0
C    4.0  18.50  12.179217   4.0  12.25  18.5  24.75  33.0

In [ ]:
df['A'].describe().T

count     4.000000
mean     28.500000
std      42.178193
min       1.000000
25%       1.000000
50%      11.500000
75%      39.000000
max      90.000000
Name: A, dtype: float64

In [83]:
df.mad()

AttributeError: 'DataFrame' object has no attribute 'mad'