In [18]:
# Aula 3
import pandas as pd

In [19]:
# carregando dataset corretamente ==> neste caso usa o separador ';'.
# It seems the separator is not ';', let's try to read the file without specifying a separator first to inspect the header.
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019.csv', sep=';', header=0)

In [20]:
data

,,8-04-14,SUL,PARANA,ETANOL HIDRATADO,371,R$/l,3.088,0.131,2.699,3.4,0.35,0.042,2.738,0.125,2.4909,3.0017,0.046,4,2018
97230,2018-04-08,2018-04-14,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,161,R$/l,3.223,0.162,2.940,3.687,0.278,0.050,2.945,0.076,2.7598,3.1147,0.026,4,2018
97231,2018-04-08,2018-04-14,NORDESTE,PIAUI,ETANOL HIDRATADO,46,R$/l,3.584,0.097,3.279,3.799,0.446,0.027,3.138,0.04,3.1355,3.2145,0.013,4,2018
97232,2018-04-08,2018-04-14,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,399,R$/l,3.741,0.188,3.190,4.199,0.426,0.050,3.315,0.142,2.96,3.7114,0.043,4,2018
97233,2018-04-08,2018-04-14,NORDESTE,RIO GRANDE DO NORTE,ETANOL HIDRATADO,59,R$/l,3.343,0.098,3.190,3.550,0.31,0.029,3.033,0.07,2.9157,3.1219,0.023,4,2018
97234,2018-04-08,2018-04-14,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,182,R$/l,4.083,0.213,3.360,4.740,0.35,0.052,3.733,0.163,3.3343,4.0201,0.044,4,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [21]:
data_final = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019_preprocessado_final.csv')

In [22]:
data_final.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [23]:
# agrupa linhas da tabela de acordo com suas respectivas regiões
grupos = data_final.groupby('REGIÃO')
grupos

In [24]:
# retorna os grupos obtidos pelo groupby
grupos.groups

{'CENTRO OESTE': [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], 'NORDESTE': [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], 'NORTE': [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], 'SUDESTE': [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], 'SUL': [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...]}

In [25]:
# retorna um dataframe apenas com as observações do grupo 'CENTRO OESTE'
grupos.indices

{'CENTRO OESTE': array([     0,      1,      2, ..., 103363, 103364, 103383]),
 'NORDESTE': array([     4,      5,      6, ..., 103385, 103387, 103391]),
 'NORTE': array([    13,     14,     15, ..., 103374, 103375, 103379]),
 'SUDESTE': array([    20,     21,     22, ..., 103377, 103386, 103390]),
 'SUL': array([    24,     25,     26, ..., 103376, 103388, 103389])}

In [26]:
# retorna um dataframe apenas com as observações do grupo 'CENTRO OESTE'
grupos.get_group('CENTRO OESTE')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
27,2004-05-16,2004-05-22,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,144,R$/l,1.271,0.039,1.060,1.300,0.448,0.031,0.823,0.111,0.4094,1.19310,0.135,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103359,2019-06-23,2019-06-29,CENTRO OESTE,DISTRITO FEDERAL,GLP,42,R$/13Kg,73.452,4.875,65.000,95.000,21.509,0.066,51.943,7.877,44.0000,62.82000,0.152,6,2019
103361,2019-06-23,2019-06-29,CENTRO OESTE,GOIAS,GLP,209,R$/13Kg,71.968,5.381,53.000,85.000,15.044,0.075,56.924,4.285,45.5700,61.60000,0.075,6,2019
103363,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO,GLP,95,R$/13Kg,96.691,6.835,73.000,115.000,19.789,0.071,76.902,8.846,61.1500,90.00000,0.115,6,2019
103364,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GLP,115,R$/13Kg,72.297,8.054,59.990,99.000,16.707,0.111,55.590,5.109,47.0000,72.00000,0.092,6,2019
103383,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GNV,2,R$/m3,2.934,0.049,2.899,2.968,0.901,0.017,2.033,0.259,1.8500,2.21610,0.127,6,2019

In [27]:
# descreva para nós algumas estatísticas descritivas para as observações de cada grupo
grupos.describe()

             NÚMERO DE POSTOS PESQUISADOS                                      \
                                    count        mean         std  min    25%
REGIÃO
CENTRO OESTE                      14545.0  144.898453  105.699340  1.0   80.0
NORDESTE                          35788.0  124.721834  113.110808  1.0   41.0
NORTE                             24000.0   67.835958   52.961342  1.0   31.0
SUDESTE                           16744.0  726.068024  787.588935  1.0  168.0
SUL                               12315.0  366.266423  233.276285  1.0  188.0

                                   PREÇO MÉDIO REVENDA             ...   MÊS  \
                50%    75%     max               count       mean  ...   75%
REGIÃO                                                             ...
CENTRO OESTE  128.0  192.0   766.0             14545.0  12.299706  ...   9.0
NORDESTE       95.0  169.0   625.0             35788.0   9.558746  ...  10.0
NORTE          53.0   95.0   383.0             24000.0  12.633086  ...   9.0
SUDESTE       412.0  996.0  4167.0             16744.0   9.828218  ...   9.0
SUL           368.0  563.0  1416.0             12315.0  10.254388  ...   9.0

                        ANO                                                 \
               max    count         mean       std     min     25%     50%
REGIÃO
CENTRO OESTE  12.0  14545.0  2011.773599  4.409036  2004.0  2008.0  2012.0
NORDESTE      12.0  35788.0  2011.704454  4.418046  2004.0  2008.0  2012.0
NORTE         12.0  24000.0  2011.812083  4.410914  2004.0  2008.0  2012.0
SUDESTE       12.0  16744.0  2011.707895  4.395436  2004.0  2008.0  2012.0
SUL           12.0  12315.0  2011.681608  4.408312  2004.0  2008.0  2012.0


                 75%     max
REGIÃO
CENTRO OESTE  2016.0  2019.0
NORDESTE      2016.0  2019.0
NORTE         2016.0  2019.0
SUDESTE       2016.0  2019.0
SUL           2015.0  2019.0

[5 rows x 112 columns]

In [32]:
# describe algumas estatísticas descritivas para as observações de cada grupo
# transforma os valores de 'data_final' em valores númericos
data_final_numerico = data_final.select_dtypes(include=['number']).columns
grupos[data_final_numerico].mean()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,
CENTRO OESTE,144.898453,12.299706,0.695078,10.610077,13.993156,2.438077,0.042077,9.861629,0.692259,8.511186,11.130478,0.039288,6.483396,2011.773599
NORDESTE,124.721834,9.558746,0.552230,8.375173,10.788018,2.069198,0.041247,7.489549,0.514093,6.563284,8.461956,0.047887,6.487845,2011.704454
NORTE,67.835958,12.633086,0.718957,11.410176,14.448137,2.221746,0.047480,10.411340,0.442566,9.505328,11.314534,0.034485,6.488458,2011.812083
SUDESTE,726.068024,9.828218,0.678608,7.966396,11.894671,2.335709,0.055126,7.492509,0.585445,6.000720,9.330476,0.060778,6.481844,2011.707895
SUL,366.266423,10.254388,0.729338,8.434376,12.391134,2.283191,0.047045,7.971197,0.726774,6.443075,9.851008,0.056162,6.476736,2011.681608

In [33]:
grupos.min()

,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.031,0.0,0.737,0.0,0.38790,0.8359,0.0,1,2004
NORDESTE,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.039,0.0,0.586,0.0,0.36320,0.5992,0.0,1,2004
NORTE,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,1.300,0.022,0.0,0.674,0.0,0.51022,0.9612,0.0,1,2004
SUDESTE,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.001,0.0,0.506,0.0,0.32570,0.7822,0.0,1,2004
SUL,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.025,0.0,0.667,0.0,0.43000,0.7044,0.0,1,2004

In [35]:
data_final.groupby('REGIÃO').min()

,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.031,0.0,0.737,0.0,0.38790,0.8359,0.0,1,2004
NORDESTE,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.039,0.0,0.586,0.0,0.36320,0.5992,0.0,1,2004
NORTE,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,1.300,0.022,0.0,0.674,0.0,0.51022,0.9612,0.0,1,2004
SUDESTE,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.001,0.0,0.506,0.0,0.32570,0.7822,0.0,1,2004
SUL,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.025,0.0,0.667,0.0,0.43000,0.7044,0.0,1,2004