In [59]:
# Aula 3
import pandas as pd

In [60]:
# carregando dataset corretamente ==> neste caso usa o separador ';'.
# It seems the separator is not ';', let's try to read the file without specifying a separator first to inspect the header.
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019.csv', sep=';', header=0)

In [61]:
data

,,8-04-14,SUL,PARANA,ETANOL HIDRATADO,371,R$/l,3.088,0.131,2.699,3.4,0.35,0.042,2.738,0.125,2.4909,3.0017,0.046,4,2018
97230,2018-04-08,2018-04-14,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,161,R$/l,3.223,0.162,2.940,3.687,0.278,0.050,2.945,0.076,2.7598,3.1147,0.026,4,2018
97231,2018-04-08,2018-04-14,NORDESTE,PIAUI,ETANOL HIDRATADO,46,R$/l,3.584,0.097,3.279,3.799,0.446,0.027,3.138,0.04,3.1355,3.2145,0.013,4,2018
97232,2018-04-08,2018-04-14,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,399,R$/l,3.741,0.188,3.190,4.199,0.426,0.050,3.315,0.142,2.96,3.7114,0.043,4,2018
97233,2018-04-08,2018-04-14,NORDESTE,RIO GRANDE DO NORTE,ETANOL HIDRATADO,59,R$/l,3.343,0.098,3.190,3.550,0.31,0.029,3.033,0.07,2.9157,3.1219,0.023,4,2018
97234,2018-04-08,2018-04-14,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,182,R$/l,4.083,0.213,3.360,4.740,0.35,0.052,3.733,0.163,3.3343,4.0201,0.044,4,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [62]:
data_final = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019_preprocessado_final.csv')

In [63]:
data_final.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [64]:
# agrupa linhas da tabela de acordo com suas respectivas regiões
grupos = data_final.groupby('REGIÃO')
grupos

In [65]:
# retorna os grupos obtidos pelo groupby
grupos.groups

{'CENTRO OESTE': [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], 'NORDESTE': [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], 'NORTE': [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], 'SUDESTE': [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], 'SUL': [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...]}

In [66]:
# retorna um dataframe apenas com as observações do grupo 'CENTRO OESTE'
grupos.indices

{'CENTRO OESTE': array([     0,      1,      2, ..., 103363, 103364, 103383]),
 'NORDESTE': array([     4,      5,      6, ..., 103385, 103387, 103391]),
 'NORTE': array([    13,     14,     15, ..., 103374, 103375, 103379]),
 'SUDESTE': array([    20,     21,     22, ..., 103377, 103386, 103390]),
 'SUL': array([    24,     25,     26, ..., 103376, 103388, 103389])}

In [67]:
# retorna um dataframe apenas com as observações do grupo 'CENTRO OESTE'
grupos.get_group('CENTRO OESTE')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
27,2004-05-16,2004-05-22,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,144,R$/l,1.271,0.039,1.060,1.300,0.448,0.031,0.823,0.111,0.4094,1.19310,0.135,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103359,2019-06-23,2019-06-29,CENTRO OESTE,DISTRITO FEDERAL,GLP,42,R$/13Kg,73.452,4.875,65.000,95.000,21.509,0.066,51.943,7.877,44.0000,62.82000,0.152,6,2019
103361,2019-06-23,2019-06-29,CENTRO OESTE,GOIAS,GLP,209,R$/13Kg,71.968,5.381,53.000,85.000,15.044,0.075,56.924,4.285,45.5700,61.60000,0.075,6,2019
103363,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO,GLP,95,R$/13Kg,96.691,6.835,73.000,115.000,19.789,0.071,76.902,8.846,61.1500,90.00000,0.115,6,2019
103364,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GLP,115,R$/13Kg,72.297,8.054,59.990,99.000,16.707,0.111,55.590,5.109,47.0000,72.00000,0.092,6,2019
103383,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GNV,2,R$/m3,2.934,0.049,2.899,2.968,0.901,0.017,2.033,0.259,1.8500,2.21610,0.127,6,2019

In [68]:
# descreva para nós algumas estatísticas descritivas para as observações de cada grupo
grupos.describe()

             NÚMERO DE POSTOS PESQUISADOS                                      \
                                    count        mean         std  min    25%
REGIÃO
CENTRO OESTE                      14545.0  144.898453  105.699340  1.0   80.0
NORDESTE                          35788.0  124.721834  113.110808  1.0   41.0
NORTE                             24000.0   67.835958   52.961342  1.0   31.0
SUDESTE                           16744.0  726.068024  787.588935  1.0  168.0
SUL                               12315.0  366.266423  233.276285  1.0  188.0

                                   PREÇO MÉDIO REVENDA             ...   MÊS  \
                50%    75%     max               count       mean  ...   75%
REGIÃO                                                             ...
CENTRO OESTE  128.0  192.0   766.0             14545.0  12.299706  ...   9.0
NORDESTE       95.0  169.0   625.0             35788.0   9.558746  ...  10.0
NORTE          53.0   95.0   383.0             24000.0  12.633086  ...   9.0
SUDESTE       412.0  996.0  4167.0             16744.0   9.828218  ...   9.0
SUL           368.0  563.0  1416.0             12315.0  10.254388  ...   9.0

                        ANO                                                 \
               max    count         mean       std     min     25%     50%
REGIÃO
CENTRO OESTE  12.0  14545.0  2011.773599  4.409036  2004.0  2008.0  2012.0
NORDESTE      12.0  35788.0  2011.704454  4.418046  2004.0  2008.0  2012.0
NORTE         12.0  24000.0  2011.812083  4.410914  2004.0  2008.0  2012.0
SUDESTE       12.0  16744.0  2011.707895  4.395436  2004.0  2008.0  2012.0
SUL           12.0  12315.0  2011.681608  4.408312  2004.0  2008.0  2012.0


                 75%     max
REGIÃO
CENTRO OESTE  2016.0  2019.0
NORDESTE      2016.0  2019.0
NORTE         2016.0  2019.0
SUDESTE       2016.0  2019.0
SUL           2015.0  2019.0

[5 rows x 112 columns]

In [69]:
# describe algumas estatísticas descritivas para as observações de cada grupo
# transforma os valores de 'data_final' em valores númericos
data_final_numerico = data_final.select_dtypes(include=['number']).columns
grupos[data_final_numerico].mean()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,
CENTRO OESTE,144.898453,12.299706,0.695078,10.610077,13.993156,2.438077,0.042077,9.861629,0.692259,8.511186,11.130478,0.039288,6.483396,2011.773599
NORDESTE,124.721834,9.558746,0.552230,8.375173,10.788018,2.069198,0.041247,7.489549,0.514093,6.563284,8.461956,0.047887,6.487845,2011.704454
NORTE,67.835958,12.633086,0.718957,11.410176,14.448137,2.221746,0.047480,10.411340,0.442566,9.505328,11.314534,0.034485,6.488458,2011.812083
SUDESTE,726.068024,9.828218,0.678608,7.966396,11.894671,2.335709,0.055126,7.492509,0.585445,6.000720,9.330476,0.060778,6.481844,2011.707895
SUL,366.266423,10.254388,0.729338,8.434376,12.391134,2.283191,0.047045,7.971197,0.726774,6.443075,9.851008,0.056162,6.476736,2011.681608

In [70]:
grupos.min()

,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.031,0.0,0.737,0.0,0.38790,0.8359,0.0,1,2004
NORDESTE,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.039,0.0,0.586,0.0,0.36320,0.5992,0.0,1,2004
NORTE,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,1.300,0.022,0.0,0.674,0.0,0.51022,0.9612,0.0,1,2004
SUDESTE,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.001,0.0,0.506,0.0,0.32570,0.7822,0.0,1,2004
SUL,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.025,0.0,0.667,0.0,0.43000,0.7044,0.0,1,2004

In [71]:
data_final.groupby('REGIÃO').min()

,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.031,0.0,0.737,0.0,0.38790,0.8359,0.0,1,2004
NORDESTE,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.039,0.0,0.586,0.0,0.36320,0.5992,0.0,1,2004
NORTE,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,1.300,0.022,0.0,0.674,0.0,0.51022,0.9612,0.0,1,2004
SUDESTE,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.001,0.0,0.506,0.0,0.32570,0.7822,0.0,1,2004
SUL,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.025,0.0,0.667,0.0,0.43000,0.7044,0.0,1,2004

Agrupamentos - 2

In [72]:
data_final.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [73]:
# Agrupa os registros do dataframe primeiramente por suas regiões
# Então, agrupa os registros de cada região (grupos) de acordo com seus produtos.
grupos = data_final.groupby(['REGIÃO', 'PRODUTO'])
grupos

In [74]:
grupos.groups

{('CENTRO OESTE', 'ETANOL HIDRATADO'): [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], ('CENTRO OESTE', 'GASOLINA COMUM'): [11980, 11981, 11982, 11983, 12007, 12008, 12009, 12010, 12034, 12035, 12036, 12037, 12061, 12062, 12063, 12064, 12088, 12089, 12090, 12091, 12115, 12116, 12117, 12118, 12142, 12143, 12144, 12145, 12169, 12170, 12171, 12172, 12196, 12197, 12198, 12199, 12223, 12224, 12225, 12226, 12250, 12251, 12252, 12253, 12277, 12278, 12279, 12280, 12304, 12305, 12306, 12307, 12331, 12332, 12333, 12334, 12358, 12359, 12360, 12361, 12385, 12386, 12387, 12388, 12412, 12413, 12414, 12415, 12439, 12440, 12441, 12442, 12466, 12467, 12468, 12469, 12493, 12494, 12495, 12496, 12520, 12521, 12522, 12523, 12547, 12548, 12549, 12550, 12574, 12575, 12576, 12577, 12601, 12602, 12603, 12604, 12628, 12629, 12630, 12631, ...], ('CENTRO OESTE', 'GLP'): [24019, 24020, 24021, 24022, 24046, 24047, 24048, 24049, 24073, 24074, 24075, 24076, 24100, 24101, 24102, 24103, 24127, 24128, 24129, 24130, 24154, 24155, 24156, 24157, 24181, 24182, 24183, 24184, 24208, 24209, 24210, 24211, 24235, 24236, 24237, 24238, 24262, 24263, 24264, 24265, 24289, 24290, 24291, 24292, 24316, 24317, 24318, 24319, 24343, 24344, 24345, 24346, 24370, 24371, 24372, 24373, 24397, 24398, 24399, 24400, 24424, 24425, 24426, 24427, 24451, 24452, 24453, 24454, 24478, 24479, 24480, 24481, 24505, 24506, 24507, 24508, 24532, 24533, 24534, 24535, 24558, 24559, 24560, 24561, 24585, 24586, 24587, 24588, 24612, 24613, 24614, 24615, 24639, 24640, 24641, 24642, 24666, 24667, 24668, 24669, ...], ('CENTRO OESTE', 'GNV'): [35892, 35907, 35922, 35937, 35952, 35967, 35982, 35997, 36012, 36027, 36042, 36057, 36072, 36087, 36102, 36117, 36132, 36147, 36162, 36177, 36192, 36207, 36222, 36237, 36252, 36267, 36283, 36298, 36313, 36329, 36345, 36360, 36375, 36390, 36405, 36420, 36436, 36451, 36466, 36481, 36495, 36510, 36525, 36541, 36557, 36572, 36588, 36604, 36620, 36635, 36650, 36665, 36680, 36695, 36710, 36725, 36740, 36755, 36770, 36785, 36800, 36815, 36830, 36845, 36860, 36875, 36890, 36918, 36932, 36948, 36962, 36991, 37006, 37021, 37037, 37053, 37068, 37084, 37100, 37116, 37132, 37148, 37164, 37180, 37196, 37212, 37228, 37244, 37259, 37275, 37291, 37307, 37323, 37339, 37355, 37371, 37387, 37403, 37419, 37435, ...], ('CENTRO OESTE', 'ÓLEO DIESEL'): [42612, 42613, 42614, 42615, 42639, 42640, 42641, 42642, 42666, 42667, 42668, 42669, 42693, 42694, 42695, 42696, 42720, 42721, 42722, 42723, 42747, 42748, 42749, 42750, 42774, 42775, 42776, 42777, 42801, 42802, 42803, 42804, 42828, 42829, 42830, 42831, 42855, 42856, 42857, 42858, 42882, 42883, 42884, 42885, 42909, 42910, 42911, 42912, 42936, 42937, 42938, 42939, 42963, 42964, 42965, 42966, 42990, 42991, 42992, 42993, 43017, 43018, 43019, 43020, 43044, 43045, 43046, 43047, 43071, 43072, 43073, 43074, 43098, 43099, 43100, 43101, 43125, 43126, 43127, 43128, 43152, 43153, 43154, 43155, 43179, 43180, 43181, 43182, 43206, 43207, 43208, 43209, 43233, 43234, 43235, 43236, 43260, 43261, 43262, 43263, ...], ('CENTRO OESTE', 'ÓLEO DIESEL S10'): [54834, 54835, 54973, 54975, 54976, 55117, 55119, 55120, 55260, 55262, 55264, 55265, 55405, 55407, 55408, 55549, 55551, 55552, 55692, 55694, 55695, 55835, 55837, 55838, 55981, 55983, 55984, 56128, 56130, 56131, 56276, 56278, 56279, 56421, 56423, 56424, 56566, 56568, 56569, 56711, 56713, 56714, 56854, 56856, 56858, 56859, 57002, 57004, 57006, 57007, 57148, 57150, 57152, 57153, 57293, 57295, 57297, 57298, 57440, 57442, 57444, 57445, 57586, 57588, 57590, 57591, 57732, 57734, 57736, 57737, 57879, 57881, 57883, 57884, 58027, 58029, 58030, 58174, 58176, 58177, 58317, 58319, 58320, 58461, 58463, 58464, 58607, 58609, 58610, 58750, 58752, 58753, 58894, 58896, 58897, 59040, 59042, 59043, 59184, 59186, ...], ('NORDESTE', 'ETANOL HIDRATADO'): [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], ('NORDESTE', 'GASOLINA COMUM'): [11984, 11985, 11986, 11987, 11988, 11989, 11990, 11991, 11992, 12011, 12012, 12013, 12014, 12015, 12016, 12017, 12018, 12019, 12038, 12039, 12040, 12041, 12042, 12043, 12044, 12045, 12046, 12065, 12066, 12067, 12068, 12069, 12070, 12071, 12072, 12073, 12092, 12093, 12094, 12095, 12096, 12097, 12098, 12099, 12100, 12119, 12120, 12121, 12122, 12123, 12124, 12125, 12126, 12127, 12146, 12147, 12148, 12149, 12150, 12151, 12152, 12153, 12154, 12173, 12174, 12175, 12176, 12177, 12178, 12179, 12180, 12181, 12200, 12201, 12202, 12203, 12204, 12205, 12206, 12207, 12208, 12227, 12228, 12229, 12230, 12231, 12232, 12233, 12234, 12235, 12254, 12255, 12256, 12257, 12258, 12259, 12260, 12261, 12262, 12281, ...], ('NORDESTE', 'GLP'): [24023, 24024, 24025, 24026, 24027, 24028, 24029, 24030, 24031, 24050, 24051, 24052, 24053, 24054, 24055, 24056, 24057, 24058, 24077, 24078, 24079, 24080, 24081, 24082, 24083, 24084, 24085, 24104, 24105, 24106, 24107, 24108, 24109, 24110, 24111, 24112, 24131, 24132, 24133, 24134, 24135, 24136, 24137, 24138, 24139, 24158, 24159, 24160, 24161, 24162, 24163, 24164, 24165, 24166, 24185, 24186, 24187, 24188, 24189, 24190, 24191, 24192, 24193, 24212, 24213, 24214, 24215, 24216, 24217, 24218, 24219, 24220, 24239, 24240, 24241, 24242, 24243, 24244, 24245, 24246, 24247, 24266, 24267, 24268, 24269, 24270, 24271, 24272, 24273, 24274, 24293, 24294, 24295, 24296, 24297, 24298, 24299, 24300, 24301, 24320, ...], ('NORDESTE', 'GNV'): [35893, 35894, 35895, 35896, 35897, 35898, 35899, 35908, 35909, 35910, 35911, 35912, 35913, 35914, 35923, 35924, 35925, 35926, 35927, 35928, 35929, 35938, 35939, 35940, 35941, 35942, 35943, 35944, 35953, 35954, 35955, 35956, 35957, 35958, 35959, 35968, 35969, 35970, 35971, 35972, 35973, 35974, 35983, 35984, 35985, 35986, 35987, 35988, 35989, 35998, 35999, 36000, 36001, 36002, 36003, 36004, 36013, 36014, 36015, 36016, 36017, 36018, 36019, 36028, 36029, 36030, 36031, 36032, 36033, 36034, 36043, 36044, 36045, 36046, 36047, 36048, 36049, 36058, 36059, 36060, 36061, 36062, 36063, 36064, 36073, 36074, 36075, 36076, 36077, 36078, 36079, 36088, 36089, 36090, 36091, 36092, 36093, 36094, 36103, 36104, ...], ('NORDESTE', 'ÓLEO DIESEL'): [42616, 42617, 42618, 42619, 42620, 42621, 42622, 42623, 42624, 42643, 42644, 42645, 42646, 42647, 42648, 42649, 42650, 42651, 42670, 42671, 42672, 42673, 42674, 42675, 42676, 42677, 42678, 42697, 42698, 42699, 42700, 42701, 42702, 42703, 42704, 42705, 42724, 42725, 42726, 42727, 42728, 42729, 42730, 42731, 42732, 42751, 42752, 42753, 42754, 42755, 42756, 42757, 42758, 42759, 42778, 42779, 42780, 42781, 42782, 42783, 42784, 42785, 42786, 42805, 42806, 42807, 42808, 42809, 42810, 42811, 42812, 42813, 42832, 42833, 42834, 42835, 42836, 42837, 42838, 42839, 42840, 42859, 42860, 42861, 42862, 42863, 42864, 42865, 42866, 42867, 42886, 42887, 42888, 42889, 42890, 42891, 42892, 42893, 42894, 42913, ...], ('NORDESTE', 'ÓLEO DIESEL S10'): [54702, 54703, 54706, 54707, 54829, 54831, 54832, 54833, 54839, 54840, 54842, 54847, 54968, 54970, 54971, 54974, 54979, 54981, 54982, 54984, 54989, 55112, 55114, 55115, 55118, 55123, 55125, 55126, 55128, 55133, 55256, 55258, 55259, 55263, 55268, 55270, 55271, 55273, 55278, 55400, 55402, 55403, 55406, 55411, 55413, 55414, 55416, 55421, 55544, 55546, 55547, 55550, 55555, 55557, 55558, 55560, 55565, 55687, 55689, 55690, 55693, 55698, 55700, 55701, 55703, 55708, 55830, 55832, 55833, 55836, 55841, 55843, 55844, 55846, 55852, 55976, 55978, 55979, 55982, 55987, 55989, 55990, 55992, 55998, 56122, 56125, 56126, 56129, 56134, 56136, 56137, 56139, 56145, 56270, 56273, 56274, 56277, 56282, 56284, 56285, ...], ('NORTE', 'ETANOL HIDRATADO'): [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], ('NORTE', 'GASOLINA COMUM'): [11993, 11994, 11995, 11996, 11997, 11998, 11999, 12020, 12021, 12022, 12023, 12024, 12025, 12026, 12047, 12048, 12049, 12050, 12051, 12052, 12053, 12074, 12075, 12076, 12077, 12078, 12079, 12080, 12101, 12102, 12103, 12104, 12105, 12106, 12107, 12128, 12129, 12130, 12131, 12132, 12133, 12134, 12155, 12156, 12157, 12158, 12159, 12160, 12161, 12182, 12183, 12184, 12185, 12186, 12187, 12188, 12209, 12210, 12211, 12212, 12213, 12214, 12215, 12236, 12237, 12238, 12239, 12240, 12241, 12242, 12263, 12264, 12265, 12266, 12267, 12268, 12269, 12290, 12291, 12292, 12293, 12294, 12295, 12296, 12317, 12318, 12319, 12320, 12321, 12322, 12323, 12344, 12345, 12346, 12347, 12348, 12349, 12350, 12371, 12372, ...], ('NORTE', 'GLP'): [24032, 24033, 24034, 24035, 24036, 24037, 24038, 24059, 24060, 24061, 24062, 24063, 24064, 24065, 24086, 24087, 24088, 24089, 24090, 24091, 24092, 24113, 24114, 24115, 24116, 24117, 24118, 24119, 24140, 24141, 24142, 24143, 24144, 24145, 24146, 24167, 24168, 24169, 24170, 24171, 24172, 24173, 24194, 24195, 24196, 24197, 24198, 24199, 24200, 24221, 24222, 24223, 24224, 24225, 24226, 24227, 24248, 24249, 24250, 24251, 24252, 24253, 24254, 24275, 24276, 24277, 24278, 24279, 24280, 24281, 24302, 24303, 24304, 24305, 24306, 24307, 24308, 24329, 24330, 24331, 24332, 24333, 24334, 24335, 24356, 24357, 24358, 24359, 24360, 24361, 24362, 24383, 24384, 24385, 24386, 24387, 24388, 24389, 24410, 24411, ...], ('NORTE', 'GNV'): [36940, 37029, 37045, 37076, 37092, 37108, 37124, 37140, 37156, 37172, 37188, 37204, 37220, 37236, 37267, 37283, 37299, 37315, 37331, 37347, 37363, 37379, 37395, 37411, 37427, 37443, 37459, 37475, 37491, 37507, 37524, 37540, 37556, 37572, 37589, 37606, 37622, 37639, 37655, 37671, 37687, 37704, 37721, 37752, 37768, 37783, 37799, 37816, 37833, 37849, 37865, 37882, 37898, 37914, 37931, 37947, 37963, 37979, 37995, 38011, 38027, 38043, 38059, 38075, 38091, 38122, 38169, 38202, 38218, 38235, 38252, 38269, 38302, 38319, 38336, 38369, 38402, 38434, 38466, 39051, 39082, 39099, 39553, 39628, 39644, 40219, 40574, 40634, 40663, 40694, 41442, 42148, 42235, 42350, 42379, 42394, 42423, 42438, 42466, 42537, ...], ('NORTE', 'ÓLEO DIESEL'): [42625, 42626, 42627, 42628, 42629, 42630, 42631, 42652, 42653, 42654, 42655, 42656, 42657, 42658, 42679, 42680, 42681, 42682, 42683, 42684, 42685, 42706, 42707, 42708, 42709, 42710, 42711, 42712, 42733, 42734, 42735, 42736, 42737, 42738, 42739, 42760, 42761, 42762, 42763, 42764, 42765, 42766, 42787, 42788, 42789, 42790, 42791, 42792, 42793, 42814, 42815, 42816, 42817, 42818, 42819, 42820, 42841, 42842, 42843, 42844, 42845, 42846, 42847, 42868, 42869, 42870, 42871, 42872, 42873, 42874, 42895, 42896, 42897, 42898, 42899, 42900, 42901, 42922, 42923, 42924, 42925, 42926, 42927, 42928, 42949, 42950, 42951, 42952, 42953, 42954, 42955, 42976, 42977, 42978, 42979, 42980, 42981, 42982, 43003, 43004, ...], ('NORTE', 'ÓLEO DIESEL S10'): [54705, 54709, 54830, 54837, 54844, 54969, 54978, 54986, 55111, 55113, 55122, 55130, 55257, 55267, 55275, 55399, 55401, 55410, 55418, 55422, 55543, 55545, 55554, 55562, 55566, 55686, 55688, 55697, 55705, 55709, 55829, 55831, 55840, 55848, 55849, 55853, 55975, 55977, 55986, 55994, 55995, 55999, 56121, 56123, 56124, 56133, 56141, 56142, 56146, 56269, 56271, 56272, 56281, 56289, 56290, 56294, 56414, 56416, 56417, 56426, 56434, 56435, 56439, 56559, 56561, 56562, 56571, 56579, 56580, 56584, 56704, 56706, 56707, 56716, 56724, 56725, 56729, 56848, 56850, 56851, 56861, 56869, 56870, 56874, 56996, 56998, 56999, 57009, 57017, 57018, 57022, 57142, 57144, 57145, 57155, 57163, 57164, 57168, 57287, 57289, ...], ('SUDESTE', 'ETANOL HIDRATADO'): [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], ('SUDESTE', 'GASOLINA COMUM'): [12000, 12001, 12002, 12003, 12027, 12028, 12029, 12030, 12054, 12055, 12056, 12057, 12081, 12082, 12083, 12084, 12108, 12109, 12110, 12111, 12135, 12136, 12137, 12138, 12162, 12163, 12164, 12165, 12189, 12190, 12191, 12192, 12216, 12217, 12218, 12219, 12243, 12244, 12245, 12246, 12270, 12271, 12272, 12273, 12297, 12298, 12299, 12300, 12324, 12325, 12326, 12327, 12351, 12352, 12353, 12354, 12378, 12379, 12380, 12381, 12405, 12406, 12407, 12408, 12432, 12433, 12434, 12435, 12459, 12460, 12461, 12462, 12486, 12487, 12488, 12489, 12513, 12514, 12515, 12516, 12540, 12541, 12542, 12543, 12567, 12568, 12569, 12570, 12594, 12595, 12596, 12597, 12621, 12622, 12623, 12624, 12648, 12649, 12650, 12651, ...], ('SUDESTE', 'GLP'): [24039, 24040, 24041, 24042, 24066, 24067, 24068, 24069, 24093, 24094, 24095, 24096, 24120, 24121, 24122, 24123, 24147, 24148, 24149, 24150, 24174, 24175, 24176, 24177, 24201, 24202, 24203, 24204, 24228, 24229, 24230, 24231, 24255, 24256, 24257, 24258, 24282, 24283, 24284, 24285, 24309, 24310, 24311, 24312, 24336, 24337, 24338, 24339, 24363, 24364, 24365, 24366, 24390, 24391, 24392, 24393, 24417, 24418, 24419, 24420, 24444, 24445, 24446, 24447, 24471, 24472, 24473, 24474, 24498, 24499, 24500, 24501, 24525, 24526, 24527, 24528, 24551, 24552, 24553, 24554, 24578, 24579, 24580, 24581, 24605, 24606, 24607, 24608, 24632, 24633, 24634, 24635, 24659, 24660, 24661, 24662, 24686, 24687, 24688, 24689, ...], ('SUDESTE', 'GNV'): [35900, 35901, 35902, 35903, 35915, 35916, 35917, 35918, 35930, 35931, 35932, 35933, 35945, 35946, 35947, 35948, 35960, 35961, 35962, 35963, 35975, 35976, 35977, 35978, 35990, 35991, 35992, 35993, 36005, 36006, 36007, 36008, 36020, 36021, 36022, 36023, 36035, 36036, 36037, 36038, 36050, 36051, 36052, 36053, 36065, 36066, 36067, 36068, 36080, 36081, 36082, 36083, 36095, 36096, 36097, 36098, 36110, 36111, 36112, 36113, 36125, 36126, 36127, 36128, 36140, 36141, 36142, 36143, 36155, 36156, 36157, 36158, 36170, 36171, 36172, 36173, 36185, 36186, 36187, 36188, 36200, 36201, 36202, 36203, 36215, 36216, 36217, 36218, 36230, 36231, 36232, 36233, 36245, 36246, 36247, 36248, 36260, 36261, 36262, 36263, ...], ('SUDESTE', 'ÓLEO DIESEL'): [42632, 42633, 42634, 42635, 42659, 42660, 42661, 42662, 42686, 42687, 42688, 42689, 42713, 42714, 42715, 42716, 42740, 42741, 42742, 42743, 42767, 42768, 42769, 42770, 42794, 42795, 42796, 42797, 42821, 42822, 42823, 42824, 42848, 42849, 42850, 42851, 42875, 42876, 42877, 42878, 42902, 42903, 42904, 42905, 42929, 42930, 42931, 42932, 42956, 42957, 42958, 42959, 42983, 42984, 42985, 42986, 43010, 43011, 43012, 43013, 43037, 43038, 43039, 43040, 43064, 43065, 43066, 43067, 43091, 43092, 43093, 43094, 43118, 43119, 43120, 43121, 43145, 43146, 43147, 43148, 43172, 43173, 43174, 43175, 43199, 43200, 43201, 43202, 43226, 43227, 43228, 43229, 43253, 43254, 43255, 43256, 43280, 43281, 43282, 43283, ...], ('SUDESTE', 'ÓLEO DIESEL S10'): [54704, 54711, 54836, 54841, 54846, 54972, 54977, 54983, 54988, 55116, 55121, 55127, 55132, 55261, 55266, 55272, 55277, 55404, 55409, 55415, 55420, 55548, 55553, 55559, 55564, 55691, 55696, 55702, 55707, 55834, 55839, 55845, 55851, 55980, 55985, 55991, 55997, 56127, 56132, 56138, 56144, 56275, 56280, 56286, 56292, 56420, 56425, 56431, 56437, 56565, 56570, 56576, 56582, 56710, 56715, 56721, 56727, 56855, 56860, 56866, 56872, 57003, 57008, 57014, 57020, 57149, 57154, 57160, 57166, 57294, 57299, 57305, 57311, 57441, 57446, 57452, 57458, 57587, 57592, 57598, 57604, 57733, 57738, 57744, 57750, 57880, 57885, 57891, 57897, 58026, 58031, 58037, 58043, 58173, 58178, 58184, 58190, 58316, 58321, 58327, ...], ('SUL', 'ETANOL HIDRATADO'): [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...], ('SUL', 'GASOLINA COMUM'): [12004, 12005, 12006, 12031, 12032, 12033, 12058, 12059, 12060, 12085, 12086, 12087, 12112, 12113, 12114, 12139, 12140, 12141, 12166, 12167, 12168, 12193, 12194, 12195, 12220, 12221, 12222, 12247, 12248, 12249, 12274, 12275, 12276, 12301, 12302, 12303, 12328, 12329, 12330, 12355, 12356, 12357, 12382, 12383, 12384, 12409, 12410, 12411, 12436, 12437, 12438, 12463, 12464, 12465, 12490, 12491, 12492, 12517, 12518, 12519, 12544, 12545, 12546, 12571, 12572, 12573, 12598, 12599, 12600, 12625, 12626, 12627, 12652, 12653, 12654, 12679, 12680, 12681, 12706, 12707, 12708, 12733, 12734, 12735, 12760, 12761, 12762, 12787, 12788, 12789, 12814, 12815, 12816, 12841, 12842, 12843, 12868, 12869, 12870, 12895, ...], ('SUL', 'GLP'): [24043, 24044, 24045, 24070, 24071, 24072, 24097, 24098, 24099, 24124, 24125, 24126, 24151, 24152, 24153, 24178, 24179, 24180, 24205, 24206, 24207, 24232, 24233, 24234, 24259, 24260, 24261, 24286, 24287, 24288, 24313, 24314, 24315, 24340, 24341, 24342, 24367, 24368, 24369, 24394, 24395, 24396, 24421, 24422, 24423, 24448, 24449, 24450, 24475, 24476, 24477, 24502, 24503, 24504, 24529, 24530, 24531, 24555, 24556, 24557, 24582, 24583, 24584, 24609, 24610, 24611, 24636, 24637, 24638, 24663, 24664, 24665, 24690, 24691, 24692, 24716, 24717, 24718, 24743, 24744, 24745, 24770, 24771, 24772, 24797, 24798, 24799, 24824, 24825, 24826, 24851, 24852, 24853, 24878, 24879, 24880, 24905, 24906, 24907, 24932, ...], ('SUL', 'GNV'): [35904, 35905, 35906, 35919, 35920, 35921, 35934, 35935, 35936, 35949, 35950, 35951, 35964, 35965, 35966, 35979, 35980, 35981, 35994, 35995, 35996, 36009, 36010, 36011, 36024, 36025, 36026, 36039, 36040, 36041, 36054, 36055, 36056, 36069, 36070, 36071, 36084, 36085, 36086, 36099, 36100, 36101, 36114, 36115, 36116, 36129, 36130, 36131, 36144, 36145, 36146, 36159, 36160, 36161, 36174, 36175, 36176, 36189, 36190, 36191, 36204, 36205, 36206, 36219, 36220, 36221, 36234, 36235, 36236, 36249, 36250, 36251, 36264, 36265, 36266, 36280, 36281, 36282, 36295, 36296, 36297, 36310, 36311, 36312, 36326, 36327, 36328, 36342, 36343, 36344, 36357, 36358, 36359, 36372, 36373, 36374, 36387, 36388, 36389, 36402, ...], ('SUL', 'ÓLEO DIESEL'): [42636, 42637, 42638, 42663, 42664, 42665, 42690, 42691, 42692, 42717, 42718, 42719, 42744, 42745, 42746, 42771, 42772, 42773, 42798, 42799, 42800, 42825, 42826, 42827, 42852, 42853, 42854, 42879, 42880, 42881, 42906, 42907, 42908, 42933, 42934, 42935, 42960, 42961, 42962, 42987, 42988, 42989, 43014, 43015, 43016, 43041, 43042, 43043, 43068, 43069, 43070, 43095, 43096, 43097, 43122, 43123, 43124, 43149, 43150, 43151, 43176, 43177, 43178, 43203, 43204, 43205, 43230, 43231, 43232, 43257, 43258, 43259, 43284, 43285, 43

In [75]:
# transforma os valores de 'data_final' em valores númericos
data_final_numerico = data_final.select_dtypes(include=['number']).columns
grupos[data_final_numerico].mean()

                               NÚMERO DE POSTOS PESQUISADOS  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO                    155.514414
             GASOLINA COMUM                      155.447352
             GLP                                 202.113944
             GNV                                   3.759150
             ÓLEO DIESEL                         131.940332
             ÓLEO DIESEL S10                      76.054545
NORDESTE     ETANOL HIDRATADO                    154.143770
             GASOLINA COMUM                      174.051678
             GLP                                 127.294072
             GNV                                  17.498068
             ÓLEO DIESEL                         135.536185
             ÓLEO DIESEL S10                      93.857190
NORTE        ETANOL HIDRATADO                     47.731312
             GASOLINA COMUM                       77.837665
             GLP                                  91.767224
             GNV                                   1.378601
             ÓLEO DIESEL                          68.135956
             ÓLEO DIESEL S10                      40.495267
SUDESTE      ETANOL HIDRATADO                   1038.720115
             GASOLINA COMUM                     1051.909236
             GLP                                 757.155881
             GNV                                  81.839493
             ÓLEO DIESEL                         771.300955
             ÓLEO DIESEL S10                     419.743514
SUL          ETANOL HIDRATADO                    454.889928
             GASOLINA COMUM                      495.972387
             GLP                                 487.431498
             GNV                                  21.242759
             ÓLEO DIESEL                         364.170348
             ÓLEO DIESEL S10                     230.283597

                               PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO             2.135670               0.111992
             GASOLINA COMUM               3.077476               0.104105
             GLP                         48.176747               2.911219
             GNV                          1.856312               0.032635
             ÓLEO DIESEL                  2.481286               0.081540
             ÓLEO DIESEL S10              3.294752               0.108976
NORDESTE     ETANOL HIDRATADO             2.320266               0.115449
             GASOLINA COMUM               3.001887               0.108104
             GLP                         41.966090               2.667713
             GNV                          1.881722               0.061486
             ÓLEO DIESEL                  2.346950               0.069301
             ÓLEO DIESEL S10              3.041966               0.091881
NORTE        ETANOL HIDRATADO             2.511624               0.123097
             GASOLINA COMUM               3.149501               0.140339
             GLP                         47.065572               2.811086
             GNV                          2.084399               0.007749
             ÓLEO DIESEL                  2.571048               0.105590
             ÓLEO DIESEL S10              3.316231               0.127927
SUDESTE      ETANOL HIDRATADO             2.163621               0.134447
             GASOLINA COMUM               3.000565               0.122024
             GLP                         42.081544               3.117192
             GNV                          1.716074               0.130730
             ÓLEO DIESEL                  2.339699               0.082670
             ÓLEO DIESEL S10              3.056194               0.109765
SUL          ETANOL HIDRATADO             2.268156               0.123595
             GASOLINA COMUM               2.972569               0.117779
             GLP                         43.490318               3.408160
             GNV                          1.865612               0.065362
             ÓLEO DIESEL                  2.332293               0.081869
             ÓLEO DIESEL S10              2.981775               0.110249

                               PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO              1.926522              2.433303
             GASOLINA COMUM                2.866732              3.338657
             GLP                          40.936969             55.244748
             GNV                           1.824489              1.885087
             ÓLEO DIESEL                   2.310497              2.686205
             ÓLEO DIESEL S10               3.070625              3.559399
NORDESTE     ETANOL HIDRATADO              2.099488              2.654045
             GASOLINA COMUM                2.780405              3.277436
             GLP                          36.142140             47.701105
             GNV                           1.820660              2.038715
             ÓLEO DIESEL                   2.203687              2.534809
             ÓLEO DIESEL S10               2.851121              3.304049
NORTE        ETANOL HIDRATADO              2.331752              2.849155
             GASOLINA COMUM                2.956946              3.540174
             GLP                          42.185523             54.103233
             GNV                           2.079103              2.091321
             ÓLEO DIESEL                   2.400341              2.831189
             ÓLEO DIESEL S10               3.128494              3.645934
SUDESTE      ETANOL HIDRATADO              1.810669              2.629952
             GASOLINA COMUM                2.698406              3.463277
             GLP                          33.297570             51.319812
             GNV                           1.548030              2.123404
             ÓLEO DIESEL                   2.118881              2.659866
             ÓLEO DIESEL S10               2.765417              3.457892
SUL          ETANOL HIDRATADO              1.947168              2.672393
             GASOLINA COMUM                2.677828              3.340463
             GLP                          34.939095             53.352339
             GNV                           1.779690              2.046901
             ÓLEO DIESEL                   2.124973              2.611223
             ÓLEO DIESEL S10               2.707439              3.366409

                               MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO              0.334742                  0.055679
             GASOLINA COMUM                0.413081                  0.033634
             GLP                          10.144382                  0.057783
             GNV                           0.467869                  0.016150
             ÓLEO DIESEL                   0.269293                  0.032117
             ÓLEO DIESEL S10               0.375726                  0.032577
NORDESTE     ETANOL HIDRATADO              0.300006                  0.052053
             GASOLINA COMUM                0.400337                  0.036357
             GLP                           9.951840                  0.060451
             GNV                           0.517594                  0.032138
             ÓLEO DIESEL                   0.233981                  0.029401
             ÓLEO DIESEL S10               0.326030                  0.030066
NORTE        ETANOL HIDRATADO              0.362131                  0.050314
             GASOLINA COMUM                0.454351                  0.045172
             GLP                           8.660637                  0.059383
             GNV                           0.371848                  0.003025
             ÓLEO DIESEL                   0.323795                  0.041224
             ÓLEO DIESEL S10               0.417151                  0.038669
SUDESTE      ETANOL HIDRATADO              0.300850                  0.064111
             GASOLINA COMUM                0.361858                  0.041105
             GLP                          10.952603                  0.070829
             GNV                           0.478567                  0.075199
             ÓLEO DIESEL                   0.261930                  0.034798
             ÓLEO DIESEL S10               0.362285                  0.035397
SUL          ETANOL HIDRATADO              0.316748                  0.055945
             GASOLINA COMUM                0.371459                  0.039308
             GLP                          10.484570                  0.075147
             GNV                           0.478205                  0.032599
             ÓLEO DIESEL                   0.276743                  0.034138
             ÓLEO DIESEL S10               0.368439                  0.036409

                               PREÇO MÉDIO DISTRIBUIÇÃO  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO                  1.800927
             GASOLINA COMUM                    2.664395
             GLP                              38.032365
             GNV                               1.388443
             ÓLEO DIESEL                       2.211993
             ÓLEO DIESEL S10                   2.919026
NORDESTE     ETANOL HIDRATADO                  2.020260
             GASOLINA COMUM                    2.601550
             GLP                              32.014250
             GNV                               1.364128
             ÓLEO DIESEL                       2.112969
             ÓLEO DIESEL S10                   2.715936
NORTE        ETANOL HIDRATADO                  2.149494
             GASOLINA COMUM                    2.695151
             GLP                              38.404935
             GNV                               1.712551
             ÓLEO DIESEL                       2.247253
             ÓLEO DIESEL S10                   2.899079
SUDESTE      ETANOL HIDRATADO                  1.862771
             GASOLINA COMUM                    2.638708
             GLP                              31.128941
             GNV                               1.237507
             ÓLEO DIESEL                       2.077769
             ÓLEO DIESEL S10                   2.693909
SUL          ETANOL HIDRATADO                  1.951408
             GASOLINA COMUM                    2.601110
             GLP                              33.005748
             GNV                               1.387408
             ÓLEO DIESEL                       2.055550
             ÓLEO DIESEL S10                   2.613336

                               DESVIO PADRÃO DISTRIBUIÇÃO  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO                    0.082278
             GASOLINA COMUM                      0.057165
             GLP                                 3.024617
             GNV                                 0.020891
             ÓLEO DIESEL                         0.049874
             ÓLEO DIESEL S10                     0.073233
NORDESTE     ETANOL HIDRATADO                    0.090895
             GASOLINA COMUM                      0.056139
             GLP                                 2.527986
             GNV                                 0.119690
             ÓLEO DIESEL                         0.048033
             ÓLEO DIESEL S10                     0.065408
NORTE        ETANOL HIDRATADO                    0.094058
             GASOLINA COMUM                      0.067774
             GLP                                 1.734085
             GNV                                 0.012959
             ÓLEO DIESEL                         0.060785
             ÓLEO DIESEL S10                     0.082405
SUDESTE      ETANOL HIDRATADO                    0.107642
             GASOLINA COMUM                      0.066199
             GLP                                 2.741245
             GNV                                 0.136902
             ÓLEO DIESEL                         0.051781
             ÓLEO DIESEL S10                     0.078823
SUL          ETANOL HIDRATADO                    0.112108
             GASOLINA COMUM                      0.064611
             GLP                                 3.461267
             GNV                                 0.113510
             ÓLEO DIESEL                         0.053771
             ÓLEO DIESEL S10                     0.081475

                               PREÇO MÍNIMO DISTRIBUIÇÃO  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO                   1.629448
             GASOLINA COMUM                     2.553451
             GLP                               32.142998
             GNV                                1.370323
             ÓLEO DIESEL                        2.106889
             ÓLEO DIESEL S10                    2.779236
NORDESTE     ETANOL HIDRATADO                   1.799990
             GASOLINA COMUM                     2.487578
             GLP                               27.493395
             GNV                                1.215388
             ÓLEO DIESEL                        2.017312
             ÓLEO DIESEL S10                    2.594516
NORTE        ETANOL HIDRATADO                   1.983308
             GASOLINA COMUM                     2.582237
             GLP                               34.773738
             GNV                                1.704218
             ÓLEO DIESEL                        2.135717
             ÓLEO DIESEL S10                    2.764806
SUDESTE      ETANOL HIDRATADO                   1.540547
             GASOLINA COMUM                     2.438181
             GLP                               24.089119
             GNV                                1.054692
             ÓLEO DIESEL                        1.931599
             ÓLEO DIESEL S10                    2.489478
SUL          ETANOL HIDRATADO                   1.634512
             GASOLINA COMUM                     2.432431
             GLP                               25.791680
             GNV                                1.233294
             ÓLEO DIESEL                        1.926497
             ÓLEO DIESEL S10                    2.438362

                               PREÇO MÁXIMO DISTRIBUIÇÃO  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO                   2.009326
             GASOLINA COMUM                     2.824949
             GLP                               43.451689
             GNV                                1.407466
             ÓLEO DIESEL                        2.323683
             ÓLEO DIESEL S10                    3.040020
NORDESTE     ETANOL HIDRATADO                   2.229782
             GASOLINA COMUM                     2.764345
             GLP                               36.713845
             GNV                                1.522437
             ÓLEO DIESEL                        2.223088
             ÓLEO DIESEL S10                    2.865362
NORTE        ETANOL HIDRATADO                   2.320192
             GASOLINA COMUM                     2.851914
             GLP                               41.960261
             GNV                                1.724462
             ÓLEO DIESEL                        2.366200
             ÓLEO DIESEL S10                    3.047200
SUDESTE      ETANOL HIDRATADO                   2.179384
             GASOLINA COMUM                     2.882938
             GLP                               39.873958
             GNV                                1.487619
             ÓLEO DIESEL                        2.256056
             ÓLEO DIESEL S10                    2.924680
SUL          ETANOL HIDRATADO                   2.240606
             GASOLINA COMUM                     2.826101
             GLP                               42.029554
             GNV                                1.512227
             ÓLEO DIESEL                        2.207007
             ÓLEO DIESEL S10                    2.814347

                               COEF DE VARIAÇÃO DISTRIBUIÇÃO       MÊS  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO                       0.049851  6.507047
             GASOLINA COMUM                         0.021549  6.507658
             GLP                                    0.076607  6.490962
             GNV                                    0.014126  6.408501
             ÓLEO DIESEL                            0.021995  6.507658
             ÓLEO DIESEL S10                        0.024829  6.329752
NORDESTE     ETANOL HIDRATADO                       0.046830  6.505819
             GASOLINA COMUM                         0.021565  6.501062
             GLP                                    0.076961  6.517317
             GNV                                    0.098374  6.490340
             ÓLEO DIESEL                            0.022107  6.501062
             ÓLEO DIESEL S10                        0.024048  6.317942
NORTE        ETANOL HIDRATADO                       0.046450  6.511686
             GASOLINA COMUM                         0.025225  6.500183
             GLP                                    0.044272  6.502722
             GNV                                    0.006025  6.485597
             ÓLEO DIESEL                            0.026873  6.498079
             ÓLEO DIESEL S10                        0.028042  6.354131
SUDESTE      ETANOL HIDRATADO                       0.060287  6.501434
             GASOLINA COMUM                         0.024951  6.500637
             GLP                                    0.087555  6.498566
             GNV                                    0.127156  6.478001
             ÓLEO DIESEL                            0.023954  6.500637
             ÓLEO DIESEL S10                        0.028969  6.318013
SUL          ETANOL HIDRATADO                       0.062075  6.501912
             GASOLINA COMUM                         0.024564  6.501274
             GLP                                    0.102631  6.516005
             GNV                                    0.082502  6.420748
             ÓLEO DIESEL                            0.025223  6.501274
             ÓLEO DIESEL S10                        0.030871  6.318182

                                       ANO
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  2011.434017
             GASOLINA COMUM    2011.430759
             GLP               2011.428341
             GNV               2010.829988
             ÓLEO DIESEL       2011.430759
             ÓLEO DIESEL S10   2015.970248
NORDESTE     ETANOL HIDRATADO  2011.421516
             GASOLINA COMUM    2011.431262
             GLP               2011.185335
             GNV               2011.103168
             ÓLEO DIESEL       2011.430676
             ÓLEO DIESEL S10   2015.759894
NORTE        ETANOL HIDRATADO  2011.228511
             GASOLINA COMUM    2011.438141
             GLP               2011.399850
             GNV               2012.016461
             ÓLEO DIESEL       2011.441537
             ÓLEO DIESEL S10   2015.786145
SUDESTE      ETANOL HIDRATADO  2011.426522
             GASOLINA COMUM    2011.433121
             GLP               2011.435448
             GNV               2011.001760
             ÓLEO DIESEL       2011.433121
             ÓLEO DIESEL S10   2015.762046
SUL          ETANOL HIDRATADO  2011.427539
             GASOLINA COMUM    2011.430331
             GLP               2011.409731
             GNV               2010.783570
             ÓLEO DIESEL       2011.430331
             ÓLEO DIESEL S10   2015.755929

In [76]:
grupos['PREÇO MÉDIO REVENDA'].describe()

                                count       mean        std     min       25%  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  3122.0   2.135670   0.561465   1.162   1.71400
             GASOLINA COMUM    3134.0   3.077476   0.615290   1.936   2.66725
             GLP               3098.0  48.176747  15.204045  28.791  37.33300
             GNV                847.0   1.856312   0.423861   1.097   1.56900
             ÓLEO DIESEL       3134.0   2.481286   0.626930   1.435   2.03300
             ÓLEO DIESEL S10   1210.0   3.294752   0.421234   2.305   2.92425
NORDESTE     ETANOL HIDRATADO  7046.0   2.320266   0.604374   1.181   1.82500
             GASOLINA COMUM    7063.0   3.001887   0.640696   1.949   2.58400
             GLP               6410.0  41.966090  12.063743  28.367  33.22875
             GNV               5176.0   1.881722   0.522996   0.975   1.59600
             ÓLEO DIESEL       7061.0   2.346950   0.605705   1.313   1.90000
             ÓLEO DIESEL S10   3032.0   3.041966   0.441550   2.130   2.60000
NORTE        ETANOL HIDRATADO  5177.0   2.511624   0.646781   1.226   2.03300
             GASOLINA COMUM    5464.0   3.149501   0.641249   1.995   2.70475
             GLP               5327.0  47.065572  14.553748  28.086  36.32950
             GNV                243.0   2.084399   0.622229   1.399   1.39900
             ÓLEO DIESEL       5465.0   2.571048   0.650994   1.450   2.08600
             ÓLEO DIESEL S10   2324.0   3.316231   0.529044   2.193   2.88300
SUDESTE      ETANOL HIDRATADO  3137.0   2.163621   0.651486   0.766   1.69200
             GASOLINA COMUM    3140.0   3.000565   0.698573   1.888   2.50200
             GLP               3137.0  42.081544  11.524738  28.026  33.63600
             GNV               2841.0   1.716074   0.462098   0.996   1.42400
             ÓLEO DIESEL       3140.0   2.339699   0.588641   1.356   1.87600
             ÓLEO DIESEL S10   1349.0   3.056194   0.418396   2.180   2.65000
SUL          ETANOL HIDRATADO  2353.0   2.268156   0.702877   0.922   1.72100
             GASOLINA COMUM    2354.0   2.972569   0.623557   1.961   2.54300
             GLP               2343.0  43.490318  11.640755  29.440  34.79250
             GNV               1899.0   1.865612   0.490703   1.168   1.49900
             ÓLEO DIESEL       2354.0   2.332293   0.527845   1.374   1.95100
             ÓLEO DIESEL S10   1012.0   2.981775   0.365470   2.151   2.66300

                                   50%       75%     max
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO   2.0005   2.47900   3.598
             GASOLINA COMUM     2.8565   3.45975   4.963
             GLP               42.8385  55.90425  99.357
             GNV                1.7490   2.16800   3.239
             ÓLEO DIESEL        2.2465   3.01900   4.162
             ÓLEO DIESEL S10    3.3540   3.61900   4.200
NORDESTE     ETANOL HIDRATADO   2.1860   2.67000   3.927
             GASOLINA COMUM     2.7410   3.42450   4.951
             GLP               36.8550  48.35100  79.630
             GNV                1.8005   2.01125   3.811
             ÓLEO DIESEL        2.0820   2.86700   4.010
             ÓLEO DIESEL S10    3.0865   3.33800   4.027
NORTE        ETANOL HIDRATADO   2.3390   2.89600   4.102
             GASOLINA COMUM     2.9330   3.58475   5.362
             GLP               42.3110  54.07500  87.270
             GNV                2.0600   2.65000   3.240
             ÓLEO DIESEL        2.3390   3.08200   4.774
             ÓLEO DIESEL S10    3.3155   3.65300   4.878
SUDESTE      ETANOL HIDRATADO   2.0430   2.56700   4.115
             GASOLINA COMUM     2.7930   3.45150   5.119
             GLP               38.2800  49.25900  79.192
             GNV                1.6630   1.90400   3.399
             ÓLEO DIESEL        2.0825   2.82500   3.994
             ÓLEO DIESEL S10    3.0910   3.38600   4.080
SUL          ETANOL HIDRATADO   2.1130   2.60100   4.287
             GASOLINA COMUM     2.7315   3.34225   4.953
             GLP               39.9760  48.73350  72.088
             GNV                1.7020   2.15950   3.476
             ÓLEO DIESEL        2.0900   2.78450   3.800
             ÓLEO DIESEL S10    2.9910   3.25200   3.815

In [77]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [None, None, None]],
                  columns=['A', 'B', 'C'])
df

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [78]:
df.agg([sum, min]) # ignora o NaN

/tmp/ipython-input-478521018.py:1: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.agg([sum, min]) # ignora o NaN
/tmp/ipython-input-478521018.py:1: FutureWarning: The provided callable <built-in function min> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.agg([sum, min]) # ignora o NaN

        A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [79]:
grupos = data_final.groupby(['REGIÃO'])
grupos

In [87]:
# Computa o menor e maior valor do 'PREÇO MÉDIO REVENDA' para cada região (grupo)
grupos['PREÇO MÉDIO REVENDA'].agg([min, max])

/tmp/ipython-input-2265528623.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  grupos['PREÇO MÉDIO REVENDA'].agg([min, max])
/tmp/ipython-input-2265528623.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grupos['PREÇO MÉDIO REVENDA'].agg([min, max])

                min     max
REGIÃO
CENTRO OESTE  1.097  99.357
NORDESTE      0.975  79.630
NORTE         1.226  87.270
SUDESTE       0.766  79.192
SUL           0.922  72.088

Ordenação

In [88]:
notas = pd.DataFrame({
    'nome': ['João', 'Maria', 'José', 'Alice'],
    'nota': [20, 21, 19, 20],
    'nota_final': [5.0, 10.0, 6.0, 10.0]
})
notas

    nome  nota  nota_final
0   João    20         5.0
1  Maria    21        10.0
2   José    19         6.0
3  Alice    20        10.0

In [89]:
notas.sort_values(by='nota_final')

    nome  nota  nota_final
0   João    20         5.0
2   José    19         6.0
1  Maria    21        10.0
3  Alice    20        10.0

In [90]:
notas.sort_values(by='nota_final', ascending=False)

    nome  nota  nota_final
1  Maria    21        10.0
3  Alice    20        10.0
2   José    19         6.0
0   João    20         5.0

In [91]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True])

    nome  nota  nota_final
3  Alice    20        10.0
1  Maria    21        10.0
2   José    19         6.0
0   João    20         5.0

In [92]:
notas

    nome  nota  nota_final
0   João    20         5.0
1  Maria    21        10.0
2   José    19         6.0
3  Alice    20        10.0

In [93]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True], inplace=True)

In [94]:
notas

    nome  nota  nota_final
3  Alice    20        10.0
1  Maria    21        10.0
2   José    19         6.0
0   João    20         5.0