In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("tips.csv")

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

## Gráfico de Barras

In [5]:
df_agrupado_pelo_dia = df.groupby("day", sort=False).agg({ "total_bill": np.sum }).reset_index()

/tmp/ipykernel_11218/1087880516.py:1: FutureWarning: The provided callable <function sum at 0x7c15c4cba950> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_agrupado_pelo_dia = df.groupby("day", sort=False).agg({ "total_bill": np.sum }).reset_index()

In [6]:
df_agrupado_pelo_dia

    day  total_bill
0   Sun     1627.16
1   Sat     1778.40
2  Thur     1096.33
3   Fri      325.88

In [7]:
px.bar(df_agrupado_pelo_dia, x="day", y="total_bill")

In [8]:
df_agrupado_pelo_dia_e_sexo = df.groupby(["day", "sex"],  sort=False).agg({ "total_bill": np.sum }).reset_index()

/tmp/ipykernel_11218/580537938.py:1: FutureWarning:

The provided callable <function sum at 0x7c15c4cba950> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

In [9]:
df_agrupado_pelo_dia_e_sexo

    day     sex  total_bill
0   Sun  Female      357.70
1   Sun    Male     1269.46
2   Sat    Male     1227.35
3   Sat  Female      551.05
4  Thur    Male      561.44
5  Thur  Female      534.89
6   Fri    Male      198.57
7   Fri  Female      127.31

In [10]:
px.bar(df_agrupado_pelo_dia_e_sexo, x="day", y="total_bill", color="sex", barmode="group")

In [11]:
px.bar(df_agrupado_pelo_dia_e_sexo, x="total_bill", y="day", color="sex", barmode="group", orientation="h")

## Gráfico de Dispersão

In [12]:
px.scatter(df, x="total_bill", y="tip", color="day", hover_name="time")

## Gráfico de Pizza

In [13]:
quantidade_pedidos_por_dia = df["day"].value_counts()

In [14]:
quantidade_pedidos_por_dia

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [15]:
quantidade_pedidos_por_dia.index

Index(['Sat', 'Sun', 'Thur', 'Fri'], dtype='object', name='day')

In [16]:
quantidade_pedidos_por_dia.values

array([87, 76, 62, 19])

In [17]:
px.pie(quantidade_pedidos_por_dia, names=quantidade_pedidos_por_dia.index, values=quantidade_pedidos_por_dia.values)