In [1]:
!pip install -u plotly

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -u

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
px.line(x=[1, 2, 3, 4, 5], y=[10, 40, 20, 50, 5])

In [4]:
df = pd.read_csv('flights.csv')

In [5]:
df.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [6]:
df.tail()

     year      month  passengers
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

In [7]:
df_agrupado_pelo_mes = df.groupby('month', sort=False).mean().reset_index()

In [8]:
df_agrupado_pelo_mes.head()

      month    year  passengers
0   January  1954.5  241.750000
1  February  1954.5  235.000000
2     March  1954.5  270.166667
3     April  1954.5  267.083333
4       May  1954.5  271.833333

In [9]:
px.line(df_agrupado_pelo_mes, x='month', y='passengers')